[supervisord]
nodaemon=true
logfile=/home/ubuntu/backend/logs/supervisord.log
pidfile=/home/ubuntu/backend/supervisord.pid

[program:digpatho_backend]
command=/home/ubuntu/backend/venv/bin/gunicorn \
    -c /home/ubuntu/backend/gunicorn_conf.py \
    app.main:app
directory=/home/ubuntu/backend
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stderr_logfile=/home/ubuntu/backend/logs/gunicorn.err.log
stdout_logfile=/home/ubuntu/backend/logs/gunicorn.out.log

environment=
    PATH="/home/ubuntu/backend/venv/bin:%(ENV_PATH)s",
    PYTHONUNBUFFERED="1",
    API_TOKEN="%(ENV_API_TOKEN)s",
    DATABASE_URL="%(ENV_DATABASE_URL)s"